FROM debian:latest
RUN apt-get update && apt-get -y install curl
CMD ["sleep", "infinity"]

---------------

FROM nginx:alpine
COPY index.html /usr/share/nginx/html
EXPOSE 80

-------------

FROM ubuntu
RUN apt-get update -y && apt-get install curl -y
WORKDIR /app
COPY ./my-troubleshooting-app.sh .
CMD ["./my-troubleshooting-app.sh"]
